server:
  port: 8010
spring:
  application:
    name: order
  datasource:
    name: orderingsystem
    url: jdbc:mysql://localhost:3306/orderingsystem?characterEncoding=UTF-8&useUnicode=true&serverTimezone=UTC
    username: root
    password: 1qaz@WSX
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.cjlu.model
